tcp:
  host: ${ROUTER_HOST:localhost}
  port: ${ROUTER_EXCHANGE_PORT:5001}

server:
  port: ${SERVER_LISTEN_PORT:8082}
  compression:
    enabled: true
  address: ${SERVER_LISTEN_ADDR:0.0.0.0}

spring:
  application:
    name: exchange-service
  main:
    web-application-type: reactive
  r2dbc:
    url: ${DB_URL:r2dbc:mariadb://localhost:3306/stock_db}
    username: ${DB_USERNAME:stock_service}
    password: ${DB_PASSWORD:stock_service_pass}

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 30
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 10                  # Renew lease every 10 seconds
    lease-expiration-duration-in-seconds: 90

#logging:
#  pattern:
#    console: "%-5level: %class{0} - %msg%n"
#  level:
#    root: INFO
#    org.springframework: INFO
#    org.springframework.boot: DEBUG
#    org.springframework.data.r2dbc: DEBUG
#    com.apress.prospring6.twenty: DEBUG