tcp:
  host: localhost
  port: 5001

server:
  port: 8082
  compression:
    enabled: true
  address: 0.0.0.0

spring:
  application:
    name: exchange-service
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:mariadb://localhost:3306/stock_db
    username: stock_service
    password: stock_service_pass

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka server URL

#logging:
#  pattern:
#    console: "%-5level: %class{0} - %msg%n"
#  level:
#    root: INFO
#    org.springframework: INFO
#    org.springframework.boot: DEBUG
#    org.springframework.data.r2dbc: DEBUG
#    com.apress.prospring6.twenty: DEBUG