exchange:
  max-amount: ${MAX_AMOUNT:1000000000}

tcp:
  host: ${ROUTER_HOST:localhost}
  port: ${ROUTER_EXCHANGE_PORT:5001}

server:
  port: ${SERVER_LISTEN_PORT:8082}
  compression:
    enabled: true
  address: ${SERVER_LISTEN_ADDR:0.0.0.0}

spring:
  application:
    name: exchange-service
  main:
    web-application-type: reactive
  r2dbc:
    url: r2dbc:${DB_HOST:mariadb}://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:stock_db}
    username: ${DB_USERNAME:stock_service}
    password: ${DB_PASSWORD:stock_pass}

eureka:
  client:
    initial-instance-info-replication-interval-seconds: 10
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

logging:
  level:
    com.rokupin.exchange: DEBUG
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN