router:
  id: R0000
  tcp:
    broker:
      host: ${ROUTER_HOST:localhost}
      port: ${ROUTER_BROKER_PORT:5000}
    exchange:
      host: ${ROUTER_HOST:localhost}
      port: ${ROUTER_EXCHANGE_PORT:5001}

server:
  port: ${SERVER_LISTEN_PORT:8083}
  compression:
    enabled: true
  address: ${SERVER_LISTEN_ADDR:0.0.0.0}

spring:
  application:
    name: router-service
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

logging:
  level:
    com.rokupin.router: DEBUG
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN