server:
  port: ${SERVER_LISTEN_PORT:8084}

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: broker-service
          uri: lb://broker-service # Use Eureka for load-balancing
          predicates:
            - Path=/ws/**
          filters:
            - StripPrefix=0 # Remove `/ws` before forwarding to broker
          metadata:
            websocket: true # Enable WebSocket routing

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
