server:
  port: ${SERVER_LISTEN_PORT:8084}

spring:
  application:
    name: gateway-service
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: broker-service
          uri: lb://broker-service
          predicates:
            - Path=/ws/**
          filters:
            - StripPrefix=0
          metadata:
            websocket: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

logging:
  level:
    com.netflix.discovery: WARN
    com.netflix.eureka: WARN