services:
  mariadb:
    build:
      context: ./mariadb
      dockerfile: Dockerfile
      args:
        DB_PORT: ${DB_PORT}
        DB_ADMIN_PASSWORD: ${DB_ADMIN_PASSWORD}
        DB_DEFAULT_USERNAME: ${DB_DEFAULT_USERNAME}
        DB_DEFAULT_PASSWORD: ${DB_DEFAULT_PASSWORD}
        DB_DEFAULT_NAME: ${DB_DEFAULT_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    networks:
      - fix-me-network
    volumes:
      - mariadb_volume:/var/lib/mysql
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  eureka-server:
    build:
      context: ../eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    environment:
      - EUREKA_PORT=${EUREKA_PORT}
      - EUREKA_HOST=eureka-server
    ports:
      - "${EUREKA_PORT}:${EUREKA_PORT}"
    networks:
      - fix-me-network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  router-service:
    build:
      context: ../router-service
      dockerfile: Dockerfile
    container_name: router-service
    environment:
      - ROUTER_HOST=router-service
      - ROUTER_BROKER_PORT=5000
      - ROUTER_EXCHANGE_PORT=5001
      - EUREKA_URI=http://eureka-server:8761/eureka/
    networks:
      - fix-me-network
    depends_on:
      - eureka-server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  broker-service:
    build:
      context: ../broker-service
      dockerfile: Dockerfile
    environment:
      - ROUTER_HOST=router-service
      - ROUTER_BROKER_PORT=5000
      - SERVER_LISTEN_PORT=8080
      - SERVER_LISTEN_ADDR=broker-service
      - EUREKA_URI=http://eureka-server:8761/eureka/
    networks:
      - fix-me-network
    depends_on:
      - eureka-server
      - router-service
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  exchange-service:
    build:
      context: ../exchange-service
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - ROUTER_HOST=router-service
      - ROUTER_EXCHANGE_PORT=5001
      - DB_URL=r2dbc:mariadb://mariadb:3306/${DB_DEFAULT_NAME}
      - EUREKA_URI=http://eureka-server:8761/eureka/
    networks:
      - fix-me-network
    depends_on:
      - mariadb
      - router-service
      - eureka-server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  gateway-service:
    build:
      context: ../gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    environment:
      - SERVER_LISTEN_PORT=${GATEWAY_PORT}
      - EUREKA_URI=http://eureka-server:${EUREKA_PORT}/eureka/
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_PORT}"
    networks:
      - fix-me-network
    depends_on:
      - eureka-server
      - broker-service
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

networks:
  fix-me-network:
    driver: bridge
volumes:
  mariadb_volume:
