tcp:
  host: ${ROUTER_HOST:localhost}
  port: ${ROUTER_BROKER_PORT:5000}

server:
  port: ${SERVER_LISTEN_PORT:8081}
  compression:
    enabled: true
  address: ${SERVER_LISTEN_ADDR:0.0.0.0}

spring:
  application:
    name: broker-service
  main:
    web-application-type: reactive

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

logging:
  level:
    com.rokupin.broker: DEBUG