server:
  port: 8081
  compression:
    enabled: true
  address: 0.0.0.0

spring:
  main:
    web-application-type: reactive

#logging:
#  pattern:
#    console: "%-5level: %class{0} - %msg%n"
#  level:
#    root: INFO
#    org.springframework: INFO
#    org.springframework.boot: DEBUG
#    org.springframework.data.r2dbc: DEBUG
#    com.apress.prospring6.twenty: DEBUG